### ISSUE TITLE
luchia.core.server:valid_host is broken

### ISSUE THREAD

**Issue by leafo** [thehunmonkgroup/luchia#1]
`string.match(self.connection.host, "^[%a%.-_]+$")`

This regular expression matches only letters or characters between `.` and `_`. Probably not what you wanted. I would switch to something like: `"^[%w._-]+$"`

**Comment by thehunmonkgroup** [comment]
There was a TODO in there to check the RFC, so I figured now was a good time to do it. RFC 1123 appears to be the one to reference, here's a summary of what it has to say about hostnames: http://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names

And here's my best effort to implement it:

``` diff
diff --git a/src/luchia/core/server.lua b/src/luchia/core/server.lua
index 00d4955..0f2eb5e 100644
--- a/src/luchia/core/server.lua
+++ b/src/luchia/core/server.lua
@@ -58,11 +58,13 @@ end

 --- Checks for a valid server host.
 -- This is an internal only method.
--- TODO: Research RFC on valid hostnames.
+-- NOTE: This regex is a best effort to follow the hostname specification in
+--       RFC 1123, but it's not perfect: some labels beginning and ending with
+--       a dash are allowed through, but are not permitted by the RFC.
 -- @return true on a valid host, nil otherwise.
 -- @usage srv:valid_host()
 local function valid_host(self)
-  if string.match(self.connection.host, "^[%a%.-_]+$") then
+  if string.match(self.connection.host, "^%w[%w%.-]+%w$") then
     return true
   else
     log:error([[Invalid host]])
```

Some cursory testing seems to indicate it works pretty well, with the noted exception in the code comments.

Thoughts?
