### ISSUE TITLE
Would it be possible to have non blocking sockets ?

### ISSUE THREAD

**Issue by 4mig4** [thehunmonkgroup/luchia#2]
Hello
Woudl it be possible to have the possilbity to use CQUEUES non blocking socket ? 

https://github.com/wahern/cqueues

**Comment by thehunmonkgroup** [comment]
I'm not familiar with that application, or the exact advantages it would provide, or how hard it would be to integrate.

Unless the integration is pretty easy and painless, it's doubtful I'd do the work myself. I would look at a pull request if there was a convincing argument for adding support.
